server:
  port: 3344

spring:
  application:
    name: cloud-config-center   #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #(哪个地址的哪个仓库的哪个分支)
          uri: https://gitee.com/gitee_xiao_wu/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: main

  #rabbitmq相关配置
  rabbitmq:
    host: 192.168.101.134
    port: 5672
    username: itcast
    password: 123321

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka       #单机地址


##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
